[project]
name = "streamingrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi>=0.136.1",
    "langchain>=1.2.15",
    "langchain-openai>=1.2.0",
    "langgraph>=1.1.9",
    "loguru>=0.7.3",
    "pandas>=3.0.2",
    "pinecone>=8.1.2",
    "requests>=2.32.5",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=5.4.1",
    "streamlit>=1.49.0",
    "uvicorn>=0.46.0",
    "langchain-nvidia-ai-endpoints>=1.2.1",
    "langchain-community>=0.4.1",
    "pypdf>=6.10.2",
    "ranx>=0.3.20",
]

[dependency-groups]
dev = [
    "ruff>=0.15.12",
]

[tool.ruff]
target-version = "py312"
line-length = 100
extend-include = ["*.ipynb"]

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
]
